#!/bin/bash

echo "🚀 Deploying to Fly.io - Run these commands:"
echo ""
echo "cd backend"
echo ""
echo "# Set secrets"
echo "fly secrets set SECRET_KEY='django-insecure-_dbg@2u6fv\$(n3slh^if%6j1c@52f7a^g@0b74mhrko!_6tmlu' --app procure-to-pay-backend"
echo "fly secrets set DEBUG=False --app procure-to-pay-backend"
echo ""
echo "# Deploy"
echo "fly deploy --app procure-to-pay-backend"
echo ""
echo "# After deployment, create demo users"
echo "fly ssh console --app procure-to-pay-backend"
echo "python manage.py create_demo_users"
echo "python manage.py collectstatic --noinput"
echo "exit"
echo ""
echo "# Test deployment"
echo "curl https://procure-to-pay-backend.fly.dev/health/"