# Generated by Django 4.2.7 on 2026-08-24 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='alert_type',
            field=models.CharField(choices=[('high_value', 'High Value Request'), ('overdue_review', 'Overdue Review'), ('budget_exceeded', 'Budget Exceeded'), ('duplicate_request', 'Duplicate Request'), ('missing_document', 'Missing Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliancealert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('report', 'Financial Report'), ('contract', 'Contract'), ('other', 'Other')], max_length=20),
        ),
    ]
