# Generated by Django 4.2.7 on 2025-11-24 09:00

import django.core.validators
from django.db import migrations, models
import procure_to_pay.apps.requests.validators


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), procure_to_pay.apps.requests.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(validators=[procure_to_pay.apps.requests.validators.validate_description]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='proforma',
            field=models.FileField(blank=True, null=True, upload_to='proformas/', validators=[procure_to_pay.apps.requests.validators.FileTypeValidator('document'), procure_to_pay.apps.requests.validators.SecureFilenameValidator()]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_order',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/', validators=[procure_to_pay.apps.requests.validators.FileTypeValidator('pdf'), procure_to_pay.apps.requests.validators.SecureFilenameValidator()]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[procure_to_pay.apps.requests.validators.FileTypeValidator('document'), procure_to_pay.apps.requests.validators.SecureFilenameValidator()]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='title',
            field=models.CharField(max_length=200, validators=[procure_to_pay.apps.requests.validators.validate_title]),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'created_at'], name='requests_pu_status_8aa348_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_by', 'status'], name='requests_pu_created_7f3272_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['amount'], name='requests_pu_amount_c33c21_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['created_at'], name='requests_pu_created_18178f_idx'),
        ),
    ]
