# Generated by Django 4.2.7 on 2025-11-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_purchaserequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
