# Generated by Django 4.2.7 on 2026-08-24 15:48

import django.core.validators
from django.db import migrations, models
import procure_to_pay.apps.requests.validators


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_purchaserequest_proforma_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), procure_to_pay.apps.requests.validators.validate_amount]),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
